### ISSUE TITLE
ETHTaipei

### ISSUE THREAD

**Issue by martinetlee** [taikoxyz/website#100]
### Title of your project

ETHTaipei

### Short (1-2 sentence) description of your project

Developer focused conference and hackathon with 1000+ participants since 2023. The event in Asia to discuss cutting-edge protocols, L2s, research, and all kinds of Interesting technology. 

### Link to your project

https://ethtaipei.org/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

we're an event that hosts highly technical content.

### Upload a quality logo to your project

![vertical (2)](https://github.com/taikoxyz/website/assets/32376541/4e6f4119-f7f8-4024-b089-5a8c0381a2bd)

**Comment by d1onys1us** [comment]
we dont consider this an ecosystem integration so closing.

**Comment by martinetlee** [comment]
@d1onys1us Kenny from your team asked me to fill in the form here. Please let me know if there are other places that I should be filling in
