### ISSUE TITLE
Add StupidMonkeys Realm Hero to the ecosystem page

### ISSUE THREAD

**Issue by FREDDStudios** [taikoxyz/website#102]
### Title of your project

StupidMonkeys Realm Hero

### Short (1-2 sentence) description of your project

Welcome to StupidMonkeys Realm Hero, where dynamic NFTs bring your monkeys to life!
Level up, evolve, and conquer in thrilling PvP battles to claim your title as the Hero of the MonkeyRealm! 

### Link to your project

https://www.stupidmonkeys.co/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

The project is fully integrated but not yet available to the public (it will launch after our marketing campaign).
Some gameplays are visible at https://app.charmverse.io/taiko/page-6542539108713263 .

### Upload a quality logo to your project

Animated logo:
![black_discord_pfp](https://github.com/taikoxyz/website/assets/100165753/27775286-f7c1-4d4d-9717-2bac89a0afbf)

Static logo:
![pfp_black (1)](https://github.com/taikoxyz/website/assets/100165753/3bb31e09-8d28-47c3-8e42-75966c514642)

**Comment by d1onys1us** [comment]
please re-open when live on testnet
