### ISSUE TITLE
New project -- iZUMi Finance 

### ISSUE THREAD

**Issue by ChuanWen107** [taikoxyz/website#113]
### Title of your project

iZUMi Finance 

### Short (1-2 sentence) description of your project

iZUMi Finance is a multi-chain DeFi protocol providing one-stop DEX-as-a-Service (DaaS) 》

### Link to your project

https://izumi.finance/home

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://alpha.izumi.finance/trade/swap

### Upload a quality logo to your project

![izumi-logo-symbol](https://github.com/taikoxyz/website/assets/103873435/236ace08-593a-4524-9c63-18431e74613a)

**Comment by 2manslkh** [comment]
we will add the izumi to the ecosystem page once it is live on testnet
