### ISSUE TITLE
ARPA Network Applying For Taiko Ecosystem Page Listing

### ISSUE THREAD

**Issue by fayarpa** [taikoxyz/website#115]
### Title of your project

ARPA Network

### Short (1-2 sentence) description of your project

ARPA Network is a threshold BLS signature scheme-based computation network. It is decentralized, secure and EVM-compatible. ARPA also builds Randcast, an on-chain verifiable RNG for tamper-proof randomness in Autonomous Worlds, gaming, and NFTs. ARPA Randcast is live on Ethereum, Optimism and Base.

### Link to your project

https://www.arpanetwork.io/en-US

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

We aim to incorporate ARPA Network and our on-chain verifiable RNG Randcast into Taiko after completing the development of our fully on-chain game DEAR and integrating ARPA Randcast into Redstone. The integration in Taiko is projected for Q2 2024.

### Upload a quality logo to your project

![ARPA_Logo_600_600](https://github.com/taikoxyz/website/assets/160837308/ecd88d0b-d484-404d-9793-be1c699b6e8d)

**Comment by 2manslkh** [comment]
we will add ARPA to the ecosystem page once it is deployed on the testnet
