### ISSUE TITLE
Request for Inclusion of Website Repository in GitPOAP Eligibility

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/website#12]
I believe that even small contributions to the project, such as those made to the website, demonstrate a meaningful engagement with the Taiko community. 

Therefore, I kindly request the inclusion of the website repository in the list of repositories that contribute to GitPOAP eligibility for 2023.

<img width="1123" alt="Capture d’écran 2023-12-06 à 17 24 55" src="https://github.com/taikoxyz/website/assets/107585158/e4b28cde-6b34-4f5f-ab8c-a7831dd38dc2">

**Comment by samui68400** [comment]
Any news guys?

**Comment by d1onys1us** [comment]
> Any news guys?

i just emailed the folks over at gitPOAP. we will try to get this added ASAP. and then take a look at the PRs which were submitted retroactively and manually reward all of them with the new POAP. thanks for pointing this out :)

**Comment by samui68400** [comment]
Thank you for your prompt response and action. Much appreciated!

**Comment by samui68400** [comment]
As per the documentation, I understand that GitPOAP bot can be manually invoked by leaving a comment. Could you please assist in invoking the GitHub bot for the website repository? I believe this will streamline the process for contributors like me.

I appreciate your attention to this matter and the swift actions taken in the past. Your support is invaluable.
