### ISSUE TITLE
Add CoastlineFi to Taiko’s ecosystem

### ISSUE THREAD

**Issue by 0x-david** [taikoxyz/website#131]
### Title of your project

CoastlineFi

### Short (1-2 sentence) description of your project

The first innovative ve(3,3)+ dex on Taiko.Hold veCSTL for invitation farming and earn 1000% APY with zero risk.

### Link to your project

https://www.coastlinefi.xyz

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Expected to launch the testnet in mid-March.

### Upload a quality logo to your project

![Logo 6](https://github.com/taikoxyz/website/assets/137024477/426bca14-0e1b-4e6c-885a-0f737ce65f2e)

**Comment by pnoken** [comment]
I've created a PR for this issue: https://github.com/taikoxyz/website/pull/132

**Comment by d1onys1us** [comment]
please re-open when live on testnet
