### ISSUE TITLE
Add KiloEx to Taiko’s ecosystem

### ISSUE THREAD

**Issue by benjamin122133** [taikoxyz/website#133]
### Title of your project

KiloEx

### Short (1-2 sentence) description of your project

Next generation of user-friendly perpetual DEX

### Link to your project

https://www.kiloex.io/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Plan to deploy on Taiko's testnets in March.

### Upload a quality logo to your project

![369071d6 (1)](https://github.com/taikoxyz/website/assets/132029451/4b5c97ab-bffa-4bac-bd69-718d4cfe4ccc)

**Comment by d1onys1us** [comment]
please re-open when live on testnet.

**Comment by benjamin122133** [comment]
<img width="577" alt="image" src="https://github.com/taikoxyz/website/assets/132029451/a520b260-12a9-4d7f-b6da-5a4d49422d2e">
