### ISSUE TITLE
B2B Collab proposal

### ISSUE THREAD

**Issue by gongguri1121** [taikoxyz/website#134]
### Title of your project

Redbrick

### Short (1-2 sentence) description of your project

Redbrick is a cloud-based web3/metaverse engine project. The engine has a maximized flexibility to integrate any chain or web3 functionality. Redbrick web3 engine empowers variety of business such as games, metaverse, education, entertainment etc.

### Link to your project

https://redbrick.land/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

-

### Upload a quality logo to your project

![Redbrick_Logo_white (1)](https://github.com/taikoxyz/website/assets/126861895/54119eb2-9bdf-4083-92a7-6e9170d9a0d6)

**Comment by gongguri1121** [comment]
Redbrick is a cloud-based web3/metaverse engine project.

Key Indicator: DAU 28k, aCCUMULATED fUNDING $20m, Revenue of 2022 $2.1m

Competitive advantage
1. Competitors: Sandbox, Decentraland (Based Unity Engine)
2. Advantage of Redbrick
- Compared to Unity, Redbrick engine is 1) Web Technology, works on any device. 2) Open Metaverse for any partnership. 3) Maximized flexibility with any feature or service. 4) Native Web3 integration (e.g. EOA / AA /  AI / Smart Contract)

**Comment by d1onys1us** [comment]
please re-open when live on testnet
