### ISSUE TITLE
EVM Warfare

### ISSUE THREAD

**Issue by harshitsiwach** [taikoxyz/website#143]
### Title of your project

Unreal Engine 5 + OmniChain + Account Abstraction

### Short (1-2 sentence) description of your project

We are a Third person shooter gaming project building on Unreal Engine which is compatible with all EVM Chains. 

### Link to your project

https://evmwarfare.com/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://mega.nz/file/MCVhCYLJ#BFVkitADnTTdbGASKYW7SoEEIfRpZ6UytA8ri9Q8rvc

### Upload a quality logo to your project

![3](https://github.com/taikoxyz/website/assets/37680927/eedcca6f-b256-42bc-9e1b-9c629f4066de)

**Comment by 2manslkh** [comment]
Duplicate #121
