### ISSUE TITLE
Add Punk Domains on the ecosystem page

### ISSUE THREAD

**Issue by tekr9d3r** [taikoxyz/website#16]
### Title of your project

Punk Domains

### Short (1-2 sentence) description of your project

Punk Domains is a modular web3 domain protocol. It allows any DAO or web3 community to launch their own TLD (domain extension) on the Taiko network.

### Link to your project

https://punk.domains/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://explorer.jolnir.taiko.xyz/token/0x4087fb91A1fBdef05761C02714335D232a2Bf3a1

### Upload a quality logo to your project

![Punk Domains - logo](https://github.com/taikoxyz/website/assets/112544892/c0389ad6-ab02-4af1-aa76-37ae044167ee)

**Comment by ameeetgaikwad** [comment]
would like to contribute!

**Comment by tekr9d3r** [comment]
The logo image on the ecosystem page has an error. Please check @2manslkh @RogerLamTd 

![Screenshot 2023-12-19 074202](https://github.com/taikoxyz/website/assets/112544892/6e86828d-c963-4e05-a97d-abccd130f2c7)
