### ISSUE TITLE
Add Kodo Exchange to the ecosystem page

### ISSUE THREAD

**Issue by drummaster98** [taikoxyz/website#165]
### Title of your project

Kodo Exchange

### Short (1-2 sentence) description of your project

Kodo is the heartbeat of Taiko's liquidity. It is a native decentralized exchange on Taiko, supercharging capital efficiency with the ve33 flywheel.

### Link to your project

https://kodo.exchange

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

It's live on Hekla. Swing by our website and give it a whirl.

### Upload a quality logo to your project

![orig-white](https://github.com/taikoxyz/website/assets/152849689/c960832d-ca15-47b4-a205-3dc300e730b7)

**Comment by bennettyong** [comment]
added to ecosystem page
