### ISSUE TITLE
xyz

### ISSUE THREAD

**Issue by jonso321** [taikoxyz/website#167]
### Title of your project

Big money

### Short (1-2 sentence) description of your project

BM

### Link to your project

Nope

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

edwed

### Upload a quality logo to your project

rfetgerg

**Comment by KorbinianK** [comment]
Spam
