### ISSUE TITLE
Add StakeEase to the ecosystem page

### ISSUE THREAD

**Issue by stakeeasecom** [taikoxyz/website#174]
### Title of your project

StakeEase

### Short (1-2 sentence) description of your project

OmniChain LRT index for higher yields, diverse rewards and streamlined LRTFi

### Link to your project

https://testnet.stakeease.com/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://testnet.stakeease.com/app/sxETH

### Upload a quality logo to your project

![Icon on Black BG](https://github.com/taikoxyz/website/assets/157893859/5279a0ff-db9a-4acb-957d-545bc602ab88)
![Icon (Light Mode)](https://github.com/taikoxyz/website/assets/157893859/46c4f10c-162e-4a18-9d65-1183824ac344)

**Comment by bennettyong** [comment]
added to ecosystem page
