### ISSUE TITLE
Add Pyth network

### ISSUE THREAD

**Issue by KemarTiti** [taikoxyz/website#176]
### Title of your project

Pyth Network

### Short (1-2 sentence) description of your project

Secure your smart contracts with reliable, low-latency market data from institutional sources. Build apps with high-fidelity oracle feeds designed for mission-critical systems.

### Link to your project

https://pyth.network/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://hekla.taikoscan.network/address/0x2880aB155794e7179c9eE2e38200202908C17B43

### Upload a quality logo to your project

![Pyth Logomark_Dark](https://github.com/taikoxyz/website/assets/84025750/1d8e2410-33fb-4eda-ae99-15cac06883e1)

**Comment by bennettyong** [comment]
added to ecosystem page
