### ISSUE TITLE
Add DaikoDEX to the ecosystem page

### ISSUE THREAD

**Issue by DaikoDex** [taikoxyz/website#177]
### Title of your project

Daikodex

### Short (1-2 sentence) description of your project

Explore advanced features and experience smooth transactions unique on Daikodex, enabling you to conduct buying and selling with utmost convenience on the Taiko Network.

### Link to your project

https://daikodex.io/swap

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://hekla.taikoscan.network/address/0xf8279Bad8Cb76B96de38365A05984b7b8f009B17

### Upload a quality logo to your project

<img width="500" alt="Daikodex logo" src="https://github.com/taikoxyz/website/assets/169646683/b1489613-7244-42e5-9dca-093ceccc75f1">

**Comment by bennettyong** [comment]
added to ecosystem
