### ISSUE TITLE
Add a Magpie Protocol to Taiko's ecosystem

### ISSUE THREAD

**Issue by ikramansari77** [taikoxyz/website#24]
### Title of your project

Magpie Protocol

### Short (1-2 sentence) description of your project

Magpie Protocol elevates crypto trading with its easy and secure token swaps across major chains. With fast, user-friendly, and non-custodial cross-chain swaps, Magpie ensures a seamless and efficient trading experience.

### Link to your project

https://www.magpiefi.xyz

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

We plan to support Taiko at the mainnet launch

### Upload a quality logo to your project

![logo-magpie-512x512](https://github.com/taikoxyz/website/assets/40393058/85350952-2936-4c34-a220-071cbf81ae7e)

**Comment by ameeetgaikwad** [comment]
would like to help!

**Comment by 2manslkh** [comment]
@ikramansari77  Could you aim to deploy a version on our testnet? We will be launching our A6 testnet soon and it will be a good place to test out your protocol!
