### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by kirk-baird** [taikoxyz/website#35]
# What is the issue?

There are some broken links on the concepts/taiko-nodes page [here](https://github.com/taikoxyz/website/blob/98f985d5e6bd8c79d2815a32f144163ff8ed97c0/pages/docs/concepts/taiko-nodes.mdx#L76-L77).

Specifically
- https://taiko.xyz/docs/concepts/creating-taiko-blocks/intrinsic-validity-functions
- https://taiko.xyz/docs/concepts/creating-taiko-blocks/intrinsic-validity-functions
- https://taikoxyz.github.io/taiko-mono/taiko-whitepaper.pdf (though maybe this is an access control issue?)

# What needs to be done?

I'm not sure where these links are meant to point. So steps to resolve are
a) Find the new address for the links
b) Update the links in `taiko-nodes.mdx`

**Comment by d1onys1us** [comment]
we have new system for autodetect broken links now.
