### ISSUE TITLE
Add Safe deployment to Taiko ecosystem

### ISSUE THREAD

**Issue by DariaLapus** [taikoxyz/website#38]
### Title of your project

Taiko Safe

### Short (1-2 sentence) description of your project

Safe is a smart contract multi-sig wallet running on Ethereum that requires a minimum number of people to approve a transaction before it can occur. Deployed by Protofire.

### Link to your project

https://safe.global/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

The Safe will be deployed in January 2024

### Upload a quality logo to your project

![TAIKO](https://github.com/taikoxyz/website/assets/91015275/4629f41b-b853-4e9c-b469-0d6ef410d87e)

**Comment by d1onys1us** [comment]
closing until live. please re-open once live.
