### ISSUE TITLE
Import auto-generated smart contract documentation from mono-repo

### ISSUE THREAD

**Issue by 2manslkh** [taikoxyz/website#4]
## Description

Currently, smart contract documentation is auto-generated using hardhat docgen and saved to `"../website/pages/docs/reference/contract-documentation/`. However, since we are removing the `website` package monorepo, the generated docs will not display on the website.

## Possible solutions
1. Add a github workflow in `taikoxyz/website` to pull smart contracts from `taikoxyz/taiko-mono:protocol` and generate docs in `taikoxyz/website`
2. Generate docs in the `taikoxyz/taiko-mono:protocol` folder and pull documentations from there.

**Comment by d1onys1us** [comment]
honestly closing this. kind of bearish on autogen documentation now. better to focus on the actual smart contract comments.
