### ISSUE TITLE
Add filtering on Taiko ecosystem page

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/website#43]
Enable filtering by label on Taiko's ecosystem page.

**Comment by Giri-Aayush** [comment]
Observation:
there is already a type made for Category of the DApp in the codebase but that is not being used anywhere.
The current layout, though informative, lacks a structured categorization system for dapps.

Proposed Solution:

1. Integrate Category Filtering: Utilize our existing Category type to implement a filtering mechanism. This will enable users to sort dapps by specific categories such as DEX, Liquid Staking, NFTs, etc.
2. Visual Categorization Enhancement: Alongside the "Live on testnet" indicator, introduce a color-coordinated system for different dapp categories.
3. Filtering Logic Development: Post-implementation, we'll need to develop a robust filtering logic to ensure seamless user experience.

**Comment by d1onys1us** [comment]
this will be coming in our new revamped website page, so closing for now.
