### ISSUE TITLE
Add language translation

### ISSUE THREAD

**Issue by d1onys1us** [taikoxyz/website#44]
Add the ability for contributors to translate the docs and have a language dropdown on the main docs website.

**Comment by Giri-Aayush** [comment]
hey @d1onys1us !
Regarding the multi-language support for our documentation, I propose the following technical approach:

- [ ] Language Selection via Survey: Conduct a survey to identify the most demanded languages from our developer community.

- [ ]  Next Steps: Post-survey, we will finalize the language list and commence the implementation phase.

- [ ] Technical Implementation:
    1. Utilize Next.js Internationalization for language-specific routing.
    2. Implement next-i18next for efficient translation management and seamless integration with Next.js.
    3. Set up subpath routing for different languages, ensuring easy navigation and accessibility.

**Comment by d1onys1us** [comment]
one of the biggest issues here FYI is our community size. unfortunately if we open up langauge translations for everyone to do, it will get airdrop farmed, and we'll deal with hundreds of pull requests that are bike shedding / trying to fix typos.

we probably need to recruit a small team of people who are effectively CODEOWNERS for certain languages. this could also help uphold quality.

maybe our language moderators in the discord could help.

**Comment by d1onys1us** [comment]
im going to close this as it belongs in docs.
