### ISSUE TITLE
Add Henjin.xyz to the ecosystem page

### ISSUE THREAD

**Issue by nekojitaxyz** [taikoxyz/website#46]
### Title of your project

Henjin.xyz

### Short (1-2 sentence) description of your project

The native Taiko DEX. Henjin is an innovative and highly flexible DEX built to support the Taiko ecosystem. Community driven and capital efficient.

### Link to your project

https://henjin.xyz

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Coming soon.

### Upload a quality logo to your project

![Henjin xyz logo](https://github.com/taikoxyz/website/assets/154665857/42e908c8-287b-4145-9591-cb811b4c7f14)

**Comment by d1onys1us** [comment]
this is awesome! for now we will close the issue. however, once it is live on testnet, you can re-open this same issue. thanks.
