### ISSUE TITLE
AICOO - A Decentralized AI co-create Platfrom

### ISSUE THREAD

**Issue by mydoto** [taikoxyz/website#51]
### Title of your project

AICOO - A Decentralized AI co-create Platfrom

### Short (1-2 sentence) description of your project

AICOO is a decentralized AI co-create platfrom. Anyone can initial a new collection and set conditions for who can paticipate. All participants co-created used AI tool and share the royalty of the collection. 

### Link to your project

https://www.aicoo.xyz/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://github.com/taikoxyz/website/assets/30818067/46b50ea5-2fb3-4703-871a-1c9c03c87820

### Upload a quality logo to your project

https://www.aicoo.xyz/_next/static/media/logo.db461150.svg

<img width="1424" alt="image" src="https://github.com/taikoxyz/website/assets/30818067/46b50ea5-2fb3-4703-871a-1c9c03c87820">

**Comment by d1onys1us** [comment]
i see this hasn't been updated for the katla testnet yet. please update and we can add it, thanks! then you can re-open this same issue.
