### ISSUE TITLE
dRPC

### ISSUE THREAD

**Issue by dRPCMarketing** [taikoxyz/website#60]
### Title of your project

dRPC

### Short (1-2 sentence) description of your project

Scale your project with new-gen decentralized RPC infrastructure. Pay-as-you-go to a global network of top-performance RPC providers supporting 30+ chains.

### Link to your project

https://drpc.org

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://taiko-jolnir.drpc.org

### Upload a quality logo to your project

<img width="512" alt="dRPC_symbol_fullcolor@2x" src="https://github.com/taikoxyz/website/assets/156195424/87416751-b6ba-401b-b4df-52596749de45">

**Comment by d1onys1us** [comment]
closing as duplicate
