### ISSUE TITLE
Request for Inclusion of Website Repository in GitPOAP Eligibility

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/website#62]
I hope this message finds you well. I wanted to follow up on the previous issue **"Request for Inclusion of Website Repository in GitPOAP Eligibility #12"** regarding the inclusion of the website repository in the list of repositories for GitPOAP eligibility.

I greatly appreciate your previous efforts and understand that things may take time. I'm keen to contribute and be a part of the community, and I was wondering if there are any updates or if there's anything specific I can do to assist with the process.

Thank you for your time and assistance.

**Comment by samui68400** [comment]
As per the documentation, I understand that GitPOAP bot can be manually invoked by leaving a comment. Could you please assist in invoking the GitHub bot for the website repository? I believe this will streamline the process for contributors like me.

I appreciate your attention to this matter and the swift actions taken in the past. Your support is invaluable.

**Comment by d1onys1us** [comment]
yes we will add anyone retroactively. we redesigned a new gitpoap for 2024 and are working with gitpoap to add this repo as well. thanks!
