### ISSUE TITLE
Noder

### ISSUE THREAD

**Issue by tlsol** [taikoxyz/website#69]
### Title of your project

noder.bot

### Short (1-2 sentence) description of your project

Nodes are complicated. We're here to change that. Setup a Taiko node in just a few clicks.

### Link to your project

https://noder.bot/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

We're already running 500+ nodes on Taiko (since Jolnir)

### Upload a quality logo to your project

![noder](https://github.com/taikoxyz/website/assets/85319459/66571e17-b0b7-48dd-9cb9-6b0bc16cdccd)

**Comment by 2manslkh** [comment]
@tlsol There is currently no way to test to spin up a taiko node, therefore it will not be added to the ecosystem for now.

**Comment by tlsol** [comment]
@2manslkh Hello, we've been active throughout Katla! Could we potentially get another look at this?
