### ISSUE TITLE
Enhancement Request: Update Documentation for Node Taiko - .env Configuration

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/website#70]
I have recently noticed a gap in the documentation related to the Node Taiko project. 

**Specifically, there is no information on how to modify the .env file to become an approver and a proposer in the following documentation https://docs.taiko.xyz/guides/run-a-taiko-node/**

I believe that addressing this gap in the documentation would greatly benefit users seeking clarity on the process. Therefore, I would like to propose adding two new chapters to cover these aspects:

**Becoming an Approver:**
Provide instructions on how to modify the .env file to attain the status of an approver within the Node Taiko project.

**Becoming a Proposer:**
Offer guidance on adjusting the .env file settings to become a proposer within the Node Taiko community.

I am willing to contribute to this enhancement by resolving the issue and updating the documentation. If you find this suggestion suitable, I would be happy to create a pull request to implement the changes.

Thank you for considering this enhancement request. I look forward to your guidance on how to proceed.

**Comment by d1onys1us** [comment]
this issue will be better in taikoxyz/docs. i'll close the issue for now as we did update our docs to include the `stn` tool.
