### ISSUE TITLE
Nomis

### ISSUE THREAD

**Issue by rroydd** [taikoxyz/website#74]
### Title of your project

Nomis

### Short (1-2 sentence) description of your project

Nomis is an identity protocol and wallet-scoring infrastructure that helps developers grow their products, services and communities faster by enabling personalized web3 experiences (think cookie infrastructure for web3). Nomis enables web3-native loyalty programs, targeting campaigns, and score-based reward distribution to improve the ROI of your marketing campaigns and prevent bots from being rewarded. We make this possible by evaluating the reputation of wallets based on their on-chain activity.

### Link to your project

https://nomis.cc/

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

We want to build Nomis Score in Taiko Network

### Upload a quality logo to your project

Nomis is an identity protocol and wallet-scoring infrastructure that helps developers grow their products, services and communities faster by enabling personalized web3 experiences (think cookie infrastructure for web3). Nomis enables web3-native loyalty programs, targeting campaigns, and score-based reward distribution to improve the ROI of your marketing campaigns and prevent bots from being rewarded. We make this possible by evaluating the reputation of wallets based on their on-chain activity.

![logo-icon-square-gradient](https://github.com/taikoxyz/website/assets/84169800/5dc88db7-1ae6-4d44-badd-b706b0ad456b)

**Comment by 2manslkh** [comment]
@rroydd Thank you for your submission. Please ping here when the project is live on testnet :)

**Comment by d1onys1us** [comment]
@rroydd closing as stale. please re-open when project is live on testnet and we'll be happy to add it.
