### ISSUE TITLE
Admeal

### ISSUE THREAD

**Issue by wild-defi** [taikoxyz/website#79]
### Title of your project

Admeal

### Short (1-2 sentence) description of your project

Admeal is an incentivized social marketplace for foodies, home cooks, and food brands that champions the rights of creators while serving as a hub for market research, innovation, and a recipe marketplace. 

### Link to your project

https://admeal.xyz

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

We deployed smart-contract on Testnet. Right now we are exploring Taiko technology to test smart accounts and NFT collectibles. 

### Upload a quality logo to your project

![admeal 512x512 x1](https://github.com/taikoxyz/website/assets/121158085/c6cc82bb-8c82-4f75-977f-9a41385441cd)

**Comment by 2manslkh** [comment]
@bakiworld Please have integrate the smart contract with a frontend UI so that users can try it out. Will add to the ecosystem page after that.

**Comment by d1onys1us** [comment]
any updates @bakiworld ? closing as stale. please re-open when you integrate @2manslkh comments.
