### ISSUE TITLE
capture

### ISSUE THREAD

**Issue by taair321** [taikoxyz/website#84]
### Title of your project

CFF

### Short (1-2 sentence) description of your project

Capture what you imagine

### Link to your project

https://www.alphamint.online/listed-nfts

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

in future i will try

**Comment by d1onys1us** [comment]
the website is not loading for me, it's just loading a spiner. if you can take a look please fix and reopen. thx
