### ISSUE TITLE
Missing Link to Katla Explorer in Taiko Documentation

### ISSUE THREAD

**Issue by samui68400** [taikoxyz/website#86]
There is currently no link to the Katla Explorer on the main documentation page of Taiko (taiko.xyz/docs). 

It would be beneficial to add a direct link either in the header or on the homepage, possibly next to the "Deploy a Contract" section.

This addition will improve user experience and make it easier for developers to access the Katla Explorer directly from the main documentation page.
<img width="1609" alt="explorer link" src="https://github.com/taikoxyz/website/assets/107585158/2a4d1b8a-0115-4c39-bb89-705d4d5872d5">

**Comment by tempe-techie** [comment]
The link to the explorer is on this page (the Frontends section): https://docs.taiko.xyz/core-concepts/what-is-taiko 

And also on the RPC config page: https://docs.taiko.xyz/network-reference/rpc-configuration

**Comment by samui68400** [comment]
I know but I believe highlighting the Katla Explorer on the main documentation page is crucial given its central role in the testnet

**Comment by d1onys1us** [comment]
this repo is for taiko.xyz, the website. the explorer is on that page, so closing for now.
