### ISSUE TITLE
DropX - Create custom Drops & Claims to bulk distribute tokens.

### ISSUE THREAD

**Issue by toshitsom** [taikoxyz/website#87]
### Title of your project

DropX

### Short (1-2 sentence) description of your project

With DropX, create public, token gated or whitelisted drops/claims for your ecosystem, project, community, friends, etc. or simply bulk distribute tokens.

### Link to your project

https://app.stationx.network/claims

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://youtu.be/pBmzLFot354

### Upload a quality logo to your project

![StationX-500px](https://github.com/taikoxyz/website/assets/22795668/5856d3d6-3dd4-439e-83f5-d61bf9950361)

**Comment by tempe-techie** [comment]
FYI: The image can't be downloaded. I suggest that you upload the PGN somewhere (e.g. on https://postimages.org/) and paste the link here.
