### ISSUE TITLE
CONTRIBUTING.md file is missing

### ISSUE THREAD

**Issue by eminmtas** [taikoxyz/website#89]
The `CONTRIBUTING.md` file that is referred in `README.md` file is missing. So, I will make a PR to guide users to go to [here](https://docs.taiko.xyz/start-here/contributing) to learn how to contribute.

**Comment by d1onys1us** [comment]
that woudl be great. i will assign you this issue.

**Comment by eminmtas** [comment]
Thank you. This PR solves the issue: #90

**Comment by paychan0108** [comment]
When I start up Bridge, balance is displayed as NA.
Once you match it to Horse or TTKO, it will be displayed if you match it to ETH.
It's cute, but I think it needs some modification.
