### ISSUE TITLE
Polymer

### ISSUE THREAD

**Issue by polyethan** [taikoxyz/website#92]
### Title of your project

Polymer

### Short (1-2 sentence) description of your project

Polymer is the Ethereum Interoperability Hub and extends secure interoperability via the Inter-Blockchain Communication protocol to other Layer 2s.

### Link to your project

polymerlabs.org

### Live on Testnet

No

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

Polymer will launch its testnet in late Q1 2024 with mainnet coming towards the start of H2 2024, at which point we will begin work to integrate Taiko.

### Upload a quality logo to your project

![symbol-png-black (2)](https://github.com/taikoxyz/website/assets/126725791/d131b2d3-ecf5-42d2-895a-06036f5d9f57)

**Comment by d1onys1us** [comment]
please re-open when live on testnet
