### ISSUE TITLE
Juhe

### ISSUE THREAD

**Issue by Gyuzsolt** [taikoxyz/website#96]
### Title of your project

Haus

### Short (1-2 sentence) description of your project

Veszejes

### Link to your project

ddd

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

dddd

### Upload a quality logo to your project

ddddd

**Comment by d1onys1us** [comment]
reported to github for spam.
