### ISSUE TITLE
Onchain-Marketplace

### ISSUE THREAD

**Issue by BlockLab-Protocol** [taikoxyz/website#98]
### Title of your project

Onchain-Marketplace

### Short (1-2 sentence) description of your project

Marketplace is a contract where you can buy and sell NFTs, like on OpenSea or Rarible.  The Onchain-Marketplace allows users to list NFTs for direct sale or auction. Other users can place offers/bids or buy the NFTs for the specified amount in the listing. The marketplace can be configured to only allow certain users to list NFTs for sale, or allow any user to list NFTs for sale.  The Marketplace contract honors EIP-2981 royalty distribution, and is integrated with the royalty registry.  Upgradeability The MarketplaceV3 contract is written in the EIP-7504 dynamic contracts pattern.   Sell your NFTs on your marketplace  Create auctions where the highest bidder, after a certain period, wins the NFT  Create an open marketplace where any user can list NFTs for sale, like OpenSea.

### Link to your project

https://onchain-marketplace.vercel.app/

### Live on Testnet

Yes (default)

### If your project is live on one of Taiko's testnets, please provide evidence of that here (eg. links, screenshots). If your project is NOT live, please provide your plan for integration here.

https://onchain-marketplace.vercel.app/

### Upload a quality logo to your project

![blocklabprotocol](https://github.com/taikoxyz/website/assets/141031631/79c23cc7-c5d4-4e68-b8e8-25f1574a22c8)

**Comment by BlockLab-Protocol** [comment]
Live on Katla testnet

**Comment by d1onys1us** [comment]
@BlockLab-Protocol could you please shorten the description to 1-2 short sentences, then i can add it. thanks

**Comment by d1onys1us** [comment]
re-open when shortened, thanks.
